### ISSUE TITLE
Error: can not expand version  to a valid semver string: fetch /2230.tidb.json from mirror(https://tiup-mirrors.pingcap.com) failed: url https://tiup-mirrors.pingcap.com/2230.tidb.json: not found

### ISSUE THREAD

**Issue by houko** [pingcap/tiup#1992]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
source ~/.zshrc
tiup playground
```

2. What did you expect to see?
successfully created a local cluster

3. What did you see instead?
```
tiup is checking updates for component playground ...
Starting component `playground`: /Users/e-hu/.tiup/components/playground/v1.10.2/tiup-playground
Error: can not expand version  to a valid semver string: fetch /2230.tidb.json from mirror(https://tiup-mirrors.pingcap.com) failed: url https://tiup-mirrors.pingcap.com/2230.tidb.json: not found
```

when I use below command 
```
tiup playground v6.2.0 --db 1 --pd 1 --kv 1 --monitor

tiup is checking updates for component playground ...
Starting component `playground`: /Users/e-hu/.tiup/components/playground/v1.10.2/tiup-playground v6.2.0 --db 1 --pd 1 --kv 1 --monitor
Flag --monitor has been deprecated, Please use --without-monitor to control whether to disable monitor.
Playground Bootstrapping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x104fba660]

goroutine 1 [running]:
main.(*Playground).terminate(0x140001b4c60, 0x9)
	github.com/pingcap/tiup/components/playground/playground.go:990 +0x340
main.execute.func3(0x14000235680?, {0x1400054ae00, 0x1, 0x8?})
	github.com/pingcap/tiup/components/playground/main.go:291 +0x918
github.com/spf13/cobra.(*Command).execute(0x14000235680, {0x140001a8010, 0x8, 0x8})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14000235680)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.execute()
	github.com/pingcap/tiup/components/playground/main.go:352 +0xbec
main.main()
	github.com/pingcap/tiup/components/playground/main.go:629 +0x30
```

4. What version of TiUP are you using (`tiup --version`)?
```
1.10.2 tiup
Go Version: go1.18.3
Git Ref: v1.10.2
GitHash: 2de5b500c9fae6d418fa200ca150b8d5264d6b19
```

**Comment by qqqdan** [comment]
Fixed. It is a mirror uploading issue.

**Comment by Hexilee** [comment]
Was this issue fixed? I still encounter this issue: `Error: Playground bootstrapping failed: fetch /2551.pd.json from mirror(https://tiup-mirrors.pingcap.com/) failed: url https://tiup-mirrors.pingcap.com/2551.pd.json: not found`.

Is there any idea to resolve it?
